# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "public"

[[redirects]]
  from = "/index.pug"
  to = "/index.html"
  force = true

[[redirects]]
  from = "/profile.pug"
  to = "/profile.html"
  force = true

[[redirects]]
  from = "/login.pug"
  to = "/login.html"
  force = true

[[redirects]]
  from = "/registration.pug"
  to = "/registration.html"
  force = true

[[redirects]]
  from = "/error404.pug"
  to = "/error404.html"
  force = true

[[redirects]]
  from = "/error500.pug"
  to = "/error500.html"
  force = true