# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "dist"

[[redirects]]
  from = "/profile"
  to = "/"
  force = true

[[redirects]]
  from = "/login"
  to = "/"
  force = true

[[redirects]]
  from = "/registration"
  to = "/"
  force = true

[[redirects]]
  from = "/error404"
  to = "/"
  force = true

[[redirects]]
  from = "/error500"
  to = "/"
  force = true